const autoprefixer = require('autoprefixer');
const purgecssModule = require('@fullhuman/postcss-purgecss');
const purgecss = purgecssModule && purgecssModule.default ? purgecssModule.default : purgecssModule;
const whitelister = require('purgecss-whitelister');

module.exports = {
  plugins: [
    autoprefixer(),
    purgecss({
      content: [
        './layouts/**/*.html',
        './content/**/*.md',
      ],
      safelist: [
        'body',
        'lazyloaded',
        'img',
        'img-fluid',
        'figure',
        'figure-img',
        'figure-caption',
        'blockquote',
        'blockquote-footer',
        'code',
        'pre',
        'table',
        'thead',
        'tbody',
        'tr',
        'th',
        'td',
        'h3',
        'alert-link',
        'flickity-slider',
        'active',
        'flickity-enabled',
        'flickity-lazyloaded',
        'is-draggable',
        'flickity-viewport',
        'menu-open',
        'top',
        'bottom',
        'headroom--not-top',
        'headroom--top',
        'windows',
        'touch',
        'btn',
        'btn-primary',
        'jobs',
        'page-item',
        'page-link',
        'option',
        'swiper',
        ...whitelister([
          './assets/scss/**/*.scss',
          //'@hyas/images/assets/scss/components/_images.scss',
          //'./assets/scss/components/_alerts.scss',
          // './assets/scss/components/_buttons.scss',
          //'./assets/scss/components/_code.scss',
          // './assets/scss/components/_syntax.scss',
        ]),
      ],
    }),
  ],
}
